steps:
  # build docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-southeast2-docker.pkg.dev/$PROJECT_ID/wesign/backend:1",
        ".",
      ]

  # push docker image to container registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "asia-southeast2-docker.pkg.dev/$PROJECT_ID/wesign/backend:1"]

  # deploy to cloud run
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
        "run",
        "deploy",
        "api-wesign",
        "--image",
        "asia-southeast2-docker.pkg.dev/$PROJECT_ID/wesign/backend:1",
        "--platform",
        "managed",
        "--region",
        "asia-southeast2",
        "--allow-unauthenticated",
        "--set-env-vars",
        "DB_HOST=$$DB_HOST,
        DB_NAME=$$DB_NAME,
        DB_USER=$$DB_USER,
        DB_PASS=$$DB_PASS",
      ]

availableSecrets:
  secretManager:
    - versionName: projects/135901466683/secrets/DB_HOST/versions/1
      env: "DB_HOST"
    - versionName: projects/135901466683/secrets/DB_NAME/versions/1
      env: "DB_NAME"
    - versionName: projects/135901466683/secrets/DB_USER/versions/1
      env: "DB_USER"
    - versionName: projects/135901466683/secrets/DB_PASS/versions/1
      env: "DB_PASS"

images:
  - "asia-southeast2-docker.pkg.dev/$PROJECT_ID/wesign/backend:1"
